apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp1
  template:
    metadata:
      labels:
        app: myapp1
    spec:
      containers:
        - name: myapp-container1
          image: docker.pkg.github.com/deepak1067/myapp/myimage:latest
          ports:
            - containerPort: 8080
          env:
          # Add environment variables here, if needed
          resources:
          # Set resource limits and requests, if needed
      imagePullSecrets:
        - name: gcr-json-key
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service1
spec:
  selector:
    app: myapp1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
