apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp2
  template:
    metadata:
      labels:
        app: myapp2
    spec:
      containers:
        - name: myapp-container2
          image: ghcr.io/deepak1067/myapp/myimage:latest
          ports:
            - containerPort: 8080
          env:
          # Add environment variables here, if needed
          resources:
          # Set resource limits and requests, if needed
      imagePullSecrets:
        - name: dockerconfigjson-github-com
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service2
spec:
  selector:
    app: myapp2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
