name: Deploy to GKE

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/deepak1067/myapp/myimage:latest
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GKE_CLUSTER: deployment-cluster-sdk
  GKE_ZONE: asia-southeast1-a

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login ghcr.io -u $DOCKER_USERNAME --password-stdin
          docker build --tag $IMAGE_NAME .
          docker push $IMAGE_NAME
          

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.4.0
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}

#      - name: Print the service account key
#        run: echo "${{ secrets.GKE_SA_KEY }}"

      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GKE_SA_KEY }}" | base64 --decode > keyfile.json
          sed -i 's/"/\\"/g' keyfile.json
          gcloud auth activate-service-account --key-file=keyfile.json


      - name: Configure Docker
        run: gcloud auth configure-docker

      - name: Deploy to GKE
        run: |
          gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
          kubectl apply -f k8s/    


#      - name: Set up Google Cloud SDK
#        uses: google-github-actions/setup-gcloud@v0.4.0
#        with:
#          project_id: ${{ secrets.PROJECT_ID }}
#          service_account_key: ${{ secrets.GKE_SA_KEY }}
#
#      - name: Authenticate with Google Cloud
#        run: echo ${{ secrets.GCLOUD_AUTH }} | base64 --decode | gcloud auth activate-service-account --key-file=-
#
#      - name: Configure Docker
#        run: gcloud auth configure-docker
#
#      - name: Download gke-auth-plugin
#        run: wget "https://github.com/ameydev/gke-auth-plugin/releases/latest/download/gke-auth-plugin" -O gke-auth-plugin
#
#      - name: Make gke-auth-plugin executable
#        run: chmod +x gke-auth-plugin
#
#      - name: Run gke-auth-plugin
#        run: ./gke-auth-plugin
#
#      - name: Get GKE cluster credentials
#        run: gcloud container clusters get-credentials $GKE_CLUSTER --zone $GKE_ZONE
#
#      - name: Deploy to GKE
#        run: |
#          kubectl apply -f k8s/
